Integration.Tests/Integration.Tests.csproj
Integration.Tests/python/test_reserved.py
PythonSourceGenerator.Tests/BasicSmokeTests.cs
PythonSourceGenerator/Keywords.cs
PythonSourceGenerator/Reflection/ArgumentReflection.cs

Mangle reserved keywords when used as identifiers

---

PythonSourceGenerator/PythonStaticGenerator.cs

Downgrading diagnostic message

---

PythonSourceGenerator/Parser/PythonSignatureParser.Function.cs

Refactor the function parser to retain Line objects

---

Integration.Tests/BasicTest.cs
PythonEnvironments/CultureExtensions.cs
PythonSourceGenerator.Tests/TestEnvironment.cs
PythonSourceGenerator.Tests/TokenizerTests.cs
PythonSourceGenerator/CaseHelper.cs
PythonSourceGenerator/Keywords.cs
PythonSourceGenerator/Parser/PythonSignatureParser.Constants.cs
PythonSourceGenerator/Parser/PythonSignatureParser.Function.cs
PythonSourceGenerator/Parser/PythonSignatureParser.Parameters.cs
PythonSourceGenerator/PythonStaticGenerator.cs
PythonSourceGenerator/Reflection/ArgumentReflection.cs
PythonSourceGenerator/Reflection/ModuleReflection.cs

Underscore literals

---

samples/Samples.sln
samples/WebApp/Program.cs
samples/WebApp/Properties/launchSettings.json
samples/WebApp/WebApp.csproj
samples/WebApp/appsettings.Development.json
samples/WebApp/appsettings.json

This pull request introduces a new `WebApp` project to the solution and configures it for development and runtime. The most important changes include adding the new project to the solution, setting up the project file with necessary dependencies, and configuring the application settings and launch settings.
* Added `WebApp` project to the solution (`samples/Samples.sln`).
* Configured build and debug settings for the new project in the solution file (`samples/Samples.sln`).
* Created `WebApp` project file with target framework, project references, and package references (`samples/WebApp/WebApp.csproj`).
* Added `Program.cs` file to set up the web application with routes and services (`samples/WebApp/Program.cs`).
* Added `launchSettings.json` for development environment configuration …

Adding web sample

---

src/CSnakes.Runtime/PyObjectTypeConverter.cs
src/CSnakes.Runtime/Python/PyObject.cs
src/CSnakes/Reflection/MethodReflection.cs

Closes #93 
Closes #91 
Closes #89 
Closes #88 
Closes #87 
Closes #86 
Closes #85 
Closes #84 
Closes #83 
Closes #81 
Closes #80

Todo cleanup and put GIL acquire in all PyObject public methods. 

---

.github/workflows/dotnet-ci.yml
README.md
docs/getting-started.md
docs/index.md
src/CSnakes.Runtime.Tests/CSnakes.Runtime.Tests.csproj
src/CSnakes.Runtime.Tests/Converter/ConverterTestBase.cs
src/CSnakes.Runtime.Tests/ServiceCollectionTests.cs
src/CSnakes.Runtime/CPython/Call.cs
src/CSnakes.Runtime/CPython/Init.cs
src/CSnakes.Runtime/IServiceCollectionExtensions.cs
src/CSnakes.Runtime/Locators/EnvironmentVariableLocator.cs
src/CSnakes.Runtime/Locators/FolderLocator.cs
src/CSnakes.Runtime/Locators/MacOSInstallerLocator.cs
src/CSnakes.Runtime/Locators/NuGetLocator.cs
src/CSnakes.Runtime/Locators/PathLocator.cs
src/CSnakes.Runtime/Locators/PythonLocationMetadata.cs
src/CSnakes.Runtime/Locators/PythonLocator.cs
src/CSnakes.Runtime/Locators/SourceLocator.cs
src/CSnakes.Runtime/Locators/WindowsInstallerLocator.cs
src/CSnakes.Runtime/Locators/WindowsStoreLocator.cs
src/CSnakes.Runtime/PythonEnvironment.cs
src/Integration.Tests/IntegrationTestBase.cs

Closes #94 
Except for Windows. We're just using the Nuget package for now.

Test a range of Python versions on macOS and Linux.

---

docs/reference.md
mkdocs.yml
src/CSnakes.Runtime.Tests/Converter/BytesConverterTest.cs
src/CSnakes.Runtime/CPython/Bytes.cs
src/CSnakes.Runtime/CPython/Call.cs
src/CSnakes.Runtime/CPython/Init.cs
src/CSnakes.Runtime/CPython/Tuple.cs
src/CSnakes.Runtime/PyObjectTypeConverter.cs
src/CSnakes.Runtime/Python/PyObject.cs
src/CSnakes/Reflection/TypeReflection.cs
src/Integration.Tests/BasicTests.cs
src/Integration.Tests/python/test_basic.py

Also implements vectorcall and closes #74 
Implements #29

Implement bytes conversion classes.

---

README.md
docs/faq.md
mkdocs.yml

Add FAQ doc

---

.github/workflows/dotnet-ci.yml

Adding .NET as matrix

---

src/CSnakes.Runtime.Tests/CSnakes.Runtime.Tests.csproj
src/CSnakes.Runtime.Tests/Converter/BoolConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/BytesConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/DictionaryConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/DoubleConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/ListConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/LongConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/TupleConverterTests.cs
src/CSnakes.Runtime.Tests/Converter/UnicodeConverterTest.cs
src/CSnakes.Runtime.Tests/Python/PyObjectTests.cs
src/CSnakes.Runtime.Tests/RuntimeTestBase.cs
src/CSnakes.Runtime/CPython/Object.cs
src/CSnakes.Runtime/Python/PyObject.cs

Also adds more tests for PyObject

Add HasAttr and GetRepr functions to PyObject

---

src/CSnakes.Runtime.Tests/Python/PyObjectTests.cs
src/CSnakes.Runtime/PyObjectTypeConverter.cs
src/CSnakes.Runtime/Python/PyObject.cs
src/CSnakes.Runtime/Python/PyTuple.cs
src/CSnakes/GeneratorError.cs
src/CSnakes/Parser/PythonParser.Parameters.cs
src/CSnakes/Parser/Types/PythonFunctionParameter.cs
src/CSnakes/Parser/Types/PythonFunctionParameterType.cs
src/CSnakes/Reflection/ArgumentReflection.cs
src/Integration.Tests/Integration.Tests.csproj
src/Integration.Tests/python/test_args.py

Support PEP570 - positional only args `/` syntax

---

src/CSnakes.Runtime.Tests/Converter/BoolConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/BytesConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/ConverterTestBase.cs
src/CSnakes.Runtime.Tests/Converter/DictionaryConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/DoubleConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/ListConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/LongConverterTest.cs
src/CSnakes.Runtime.Tests/Converter/TupleConverterTests.cs
src/CSnakes.Runtime.Tests/Converter/UnicodeConverterTest.cs
src/CSnakes.Runtime/Python/PyObject.cs

Refactored tests to use the new API

Public method for creating a PyObject from a CLR type.

---

src/CSnakes.Runtime/Locators/NuGetLocator.cs

Use NUGET_PACKAGES override in Nuget locator

---

samples/Aspire/python/otlp_tracing.py
samples/Aspire/python/weather.py

Fixed the SQL traces for the Python app.

Aspire tracing tweaks

---

src/Integration.Tests/FalseReturns.cs
src/Integration.Tests/python/test_false_returns.py

Add integer overflow test

---

.github/workflows/dotnet-ci.yml
Directory.Build.props
samples/Aspire/CSnakesAspire.ApiService/CSnakesAspire.ApiService.csproj
samples/simple/QuickConsoleTest/QuickConsoleTest.csproj
samples/simple/WebApp/WebApp.csproj
src/CSnakes.Runtime.Tests/CSnakes.Runtime.Tests.csproj
src/Directory.Build.props
src/Integration.Tests/Integration.Tests.csproj
src/Profile/Profile.csproj

Use CI version of Python

---

src/CSnakes.Runtime.Tests/CSnakes.Runtime.Tests.csproj
src/CSnakes.Runtime.Tests/RuntimeTestBase.cs
src/CSnakes.Runtime/IServiceCollectionExtensions.cs
src/CSnakes.Runtime/Locators/EnvironmentVariableLocator.cs
src/CSnakes.Runtime/Locators/NuGetLocator.cs
src/Integration.Tests/IntegrationTestBase.cs
src/Profile/BaseBenchmark.cs

Run Windows tests against the supplied Python version

---

src/CSnakes.SourceGeneration/Parser/Types/PythonConstant.cs
src/CSnakes.Tests/PythonConstantTests.cs

Use invariant culture when converting float constant to string

---

src/CSnakes.SourceGeneration/PythonStaticGenerator.cs
src/CSnakes.Tests/GeneratedSignatureTests.cs

This PR addresses a [review suggestion](https://github.com/tonybaloney/CSnakes/pull/259#discussion_r1797696168) on PR #259.

Use content hash for the module

---

src/CSnakes.SourceGeneration/Reflection/TypeReflection.cs

This PR consolidates three patterns into one for `IPyBuffer`.

Consolidate patterns for `IPyBuffer`

---

src/CSnakes.Runtime/IReloadableModuleImport.cs
src/CSnakes.SourceGeneration/PythonStaticGenerator.cs
src/Integration.Tests/python/test_reload.py

This PR demonstrates an [idea being discussed](https://github.com/tonybaloney/CSnakes/pull/259#discussion_r1797715811) in PR #259.

Have `ReloadModule` inherited/implemented through an interface

---

src/CSnakes.Tests/GeneratedSignatureTests.cs

This PR proposes to make the generated signature tests stricter by using `Assert.Equal` instead of `Assert.Contains`. Besides avoiding accidental matches, this change provides better assertion failures. With `Assert.Contains`, the error looks as follows:
Xunit.Sdk.ContainsException
Assert.Contains() Failure: Sub-string not found
String:    "public void Hello(long? b = null)\r\n{\r\n   "···
Not found: "void Hello(long? a = null)"
With `Assert.Equal`, one gets better information such as where the first difference occurs:
Xunit.Sdk.EqualException
Assert.Equal() Failure: Strings differ
↓ (pos 24)
Expected: "public void Hello(long? a = null)"
Actual:   "public void Hello(long? b = null)"
↑ (pos 24)
This helps in being able to spot and fix problems quicker.

Make generated signature tests stricter

---

.github/workflows/dotnet-ci.yml
src/CSnakes.Runtime.Tests/Python/ImmortalTests.cs
src/CSnakes.Runtime/Python/Interns/ImmortalSmallInteger.cs
src/CSnakes.Runtime/Python/Interns/PyFalseObject.cs
src/CSnakes.Runtime/Python/Interns/PyNegativeOneObject.cs
src/CSnakes.Runtime/Python/Interns/PyOneObject.cs
src/CSnakes.Runtime/Python/Interns/PyTrueObject.cs
src/CSnakes.Runtime/Python/Interns/PyZeroObject.cs
src/CSnakes.Runtime/Python/PyObject.Imortals.cs
src/CSnakes.Runtime/Python/PyObject.cs

Immortalising -1, 0 and 1

---

src/CSnakes.Runtime/CPython/Init.cs
src/CSnakes.Runtime/PythonEnvironment.cs

Alternative proposal to https://github.com/tonybaloney/CSnakes/pull/263.

Use `System.Threading.Lock` on .NET 9.

---

samples/simple/README.md

Small PR - Commit ed4def2d98610438016bf7e72250ed89a5478b97 moved samples to `samples/simple`. This PR adjusts sources to changes.

Update samples/simple references

---

.github/workflows/dotnet-ci.yml
src/CSnakes.Runtime/EnvironmentManagement/CondaEnvironmentManagement.cs
src/CSnakes.Runtime/EnvironmentManagement/IEnvironmentManagement.cs
src/CSnakes.Runtime/PythonEnvironmentBuilder.cs
src/Conda.Tests/CondaTestBase.cs

Ensure conda envs exists in testing

---

src/CSnakes.Runtime/PackageManagement/UVInstaller.cs
src/CSnakes.Runtime/ProcessUtils.cs

reduce package installer noise in logs

---

src/CSnakes.Runtime.Tests/RuntimeTestBase.cs
src/CSnakes.Runtime/Locators/NuGetLocator.cs
src/CSnakes.Runtime/Locators/WindowsStoreLocator.cs
src/Integration.Tests/IntegrationTestBase.cs

Add ARM64 on Windows path locators

---

src/CSnakes.SourceGeneration/Parser/PythonParser.Parameters.cs
src/CSnakes.Tests/TokenizerTests.cs

Allow trailing commas in parameter list

---

.github/workflows/dotnet-ci.yml
src/CSnakes.Runtime/ProcessUtils.cs

Create no window on pip and virtualenv commands

---

src/Conda.Tests/CondaTestBase.cs

Check if the anaconda3 directory exists and if not, change it to miniconda3.
Second attempt :D

Allow run Conda tests with Miniconda3

---

README.md

The project is more stable now, so I removed the prototype warning from the README file.

Remove prototype warning

---

src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_buffer.approved.txt
src/Integration.Tests/BufferTests.cs
src/Integration.Tests/python/test_buffer.py

This is included in the examples now, so we need a test for it.

Add a generator buffer test

---

src/CSnakes.Runtime.Tests/Converter/TupleConverterTests.cs

This PR is a follow-up to:
1. https://github.com/tonybaloney/CSnakes/pull/413#discussion_r2053368750
1. https://github.com/tonybaloney/CSnakes/pull/413#discussion_r2053368941

Use positional ordinals consistently for tuple test data

---

docs/performance.md
mkdocs.yml

Add a doc page on performance considerations

---

docs/async_support.md

This PR updates the doc based on #353 being addressed.

Refresh doc on `CancellationToken` support

---

docs/async_support.md
src/CSnakes.SourceGeneration/Reflection/MethodReflection.cs
src/CSnakes.SourceGeneration/Reflection/TypeReflection.cs
src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_coroutines.approved.txt
src/Integration.Tests/python/test_coroutines.py
src/Profile/async_benchmarks.py
src/Profile/marshalling_benchmarks.py

Implement `async def f() -> T` -> `Task<T>`

Simple async return type syntax

---

.github/workflows/dotnet-ci.yml

Add .NET 10 preview 4 to test pipelines

---

docs/advanced.md
src/CSnakes.Runtime.Tests/PythonEnvironmentBuilderTests.cs
src/CSnakes.Runtime/CPython/Init.cs
src/CSnakes.Runtime/IPythonEnvironmentBuilder.cs
src/CSnakes.Runtime/Locators/PythonLocationMetadata.cs
src/CSnakes.Runtime/PythonEnvironment.cs
src/CSnakes.Runtime/PythonEnvironmentBuilder.cs
src/CSnakes.Runtime/PythonEnvironmentOptions.cs
src/RedistributablePython.Tests/RedistributablePythonTestBase.cs

Add override to disable signal handlers and document it

---

src/CSnakes.SourceGeneration/Reflection/ArgumentReflection.cs
src/CSnakes.Tests/GeneratedSignatureTests.cs
src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_defaults.approved.txt

Fix nullability of default value types

---

src/CSnakes.SourceGeneration/Reflection/MethodDefinitionComparator.cs
src/CSnakes.Tests/GeneratedSignatureTests.cs

Ensure overloads for nullable and non-nullable equivalent types are not generated

---

.github/dependabot.yml
src/Directory.Packages.props

Downgrade C# code analysis

---

templates/src/CSnakes.Templates.csproj
templates/src/ConsoleApp/ConsoleApp.1.csproj

Improves compatibility with 9.0.103 SDK

Update template to use 1.2.1

---

docs/requirements.txt
mkdocs.yml

Implements #626 
Needs manual publishing and changing the docs branch

Setup mike on docs

---

.devcontainer/devcontainer.json

Running the dev container and then `dotnet build src` produces the following errors:
CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.ConfigureGeneratedCodeAnalysisAnalyzer cannot be created from /root/.nuget/packages/microsoft.codeanalysis.analyzers/4.14.0/analyzers/dotnet/cs/Microsoft.CodeAnalysis.Analyzers.dll : Could not load file or assembly 'System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.. [/workspaces/CSnakes/src/CSnakes.SourceGeneration/CSnakes.SourceGeneration.csproj::TargetFramework=netstandard2.0]
CSC : error CS8032: An instance of analyzer Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerAttributeAnalyzer cannot be created from …

Fix dev container: .NET 9 SDK & submodule init + update
