- Integration.Tests/Integration.Tests.csproj
- Integration.Tests/python/test_keywords.py
- PythonSourceGenerator.Tests/BasicSmokeTests.cs
- PythonSourceGenerator.Tests/TokenizerTests.cs
- PythonSourceGenerator/Parser/PythonSignatureParser.cs
- PythonSourceGenerator/Parser/Types/PythonFunctionDefinition.cs
- PythonSourceGenerator/Parser/Types/PythonFunctionParameter.cs
- PythonSourceGenerator/Parser/Types/PythonFunctionParameterType.cs
- PythonSourceGenerator/Reflection/ArgumentReflection.cs
> Implement keyword only args and allow unnamed star args per PEP3102

- Integration.Tests/python/test_defaults.py
- PythonSourceGenerator.Tests/BasicSmokeTests.cs
- PythonSourceGenerator.Tests/TokenizerTests.cs
- PythonSourceGenerator/Parser/PythonSignatureParser.Constants.cs
- PythonSourceGenerator/Parser/PythonSignatureTokenizer.cs
- PythonSourceGenerator/Parser/PythonSignatureTokens.cs
- PythonSourceGenerator/Parser/Types/PythonConstant.cs
- PythonSourceGenerator/Reflection/ArgumentReflection.cs
Also changes the parser to emit `long` instead of `int` for literals.
Closes #39 
Doesn't include Octal literals as C# doesn't support those anyway.
The emitted literals are formatted in binary or hexidecimal if Python was that way.
> Parse Hexidecimal and Binary literals as Integers

- PythonSourceGenerator.Tests/BasicSmokeTests.cs
- PythonSourceGenerator.Tests/TokenizerTests.cs
- PythonSourceGenerator/Parser/PythonSignatureParser.Function.cs
- PythonSourceGenerator/PythonStaticGenerator.cs
Using the source generator to read the file in, which gives us lines and column (span) count.
This can help pin-point errors a little easier.
Fixes #40
> Error tracking

- src/CSnakes.Runtime/CPython/Mapping.cs
- src/CSnakes.Runtime/CPython/Object.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.cs
- src/CSnakes.Runtime/Python/PyObject.cs
- src/CSnakes.Runtime/PythonInvocationException.cs
- src/CSnakes.Runtime/PythonRuntimeException.cs
- src/Integration.Tests/ExceptionTests.cs
- src/Integration.Tests/python/test_exceptions.py
`PythonException` is now `PythonInvocationException`.
It always has an innerexception of `PythonRuntimeException`.
> Capture Python stack traces and frame data for easier debugging

- .github/workflows/dotnet-publish-ci.yml
- .github/workflows/dotnet-publish-main.yml
- .github/workflows/dotnet-publish-release.yml
- src/Directory.Build.props
Since DebugType is embedded the PDBs aren't generated, instead the metadata for that is put into the DLL that the compiler generates. We then don't need to generate a snupkg since that won't contain anything (there's no PDB), so we don't need to publish that anywhere.
Also, IncludeSymbols isn't 'add symbols to the build output' but 'create a symbols NuGet package'. See https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#includesymbols
> Fixing how we generate packages with debug info

- src/CSnakes.Runtime/PyObjectTypeConverter.Dictionary.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.Generator.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.List.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.Tuple.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.cs
- **Removing a method that we don't really need**
- **Caching the constructors for the types we discover on the fly**
> type converter perf

- docs/reference.md
- src/CSnakes.Runtime.Tests/Python/PyObjectTests.cs
- src/CSnakes.Runtime/CPython/Object.cs
- src/CSnakes.Runtime/Python/PyObject.cs
Also adds operator overloads. 
This now works:
```csharp
// Test rich comparisons of mixed types
var obj11 = PyObject.From(3.0);
var obj12 = PyObject.From(3);
Assert.True(obj11!.Equals(obj12!));
Assert.True(obj11 == obj12);
```
> Add methods to `PyObject` for `Is`, `Equals` and `NotEquals`

- src/CSnakes.Runtime/PackageManagement/PipInstaller.cs
- src/CSnakes.Runtime/PythonEnvironment.cs
- src/CSnakes/Reflection/MethodReflection.cs
* Also adds a flag to `pip` installer saying don't check for new versions because there is _always_ a new version and it writes the output to stderr which looks like something bad happened in the Aspire Logs.
> Chill the logging out a bit

- src/CSnakes.Runtime.Tests/Python/PyObjectTests.cs
- src/CSnakes.Runtime/Python/PyObject.cs
Fixes #153 
Not sure how to write a test for this. Since the source generator mostly converts `PyObject`s to natural .NET types, I don't know where to write the test and am very ignorant of how to create an "object" in Python that forces the generator to not return a `long` for the following signature: `def int_one() -> int:`.
> Implement <, >, <=, >=

- src/CSnakes.Runtime.Tests/Python/PyObjectTests.cs
- src/CSnakes.Runtime.Tests/RuntimeTestBase.cs
- src/CSnakes.Runtime/CPython/Dict.cs
- src/CSnakes.Runtime/CPython/Float.cs
- src/CSnakes.Runtime/CPython/Import.cs
- src/CSnakes.Runtime/CPython/List.cs
- src/CSnakes.Runtime/CPython/Long.cs
- src/CSnakes.Runtime/CPython/Object.cs
- src/CSnakes.Runtime/CPython/Tuple.cs
- src/CSnakes.Runtime/CPython/Unicode.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.BigInteger.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.Dictionary.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.Generator.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.List.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.Tuple.cs
- src/CSnakes.Runtime/PyObjectTypeConverter.cs
- src/CSnakes.Runtime/Python/GIL.cs
- src/CSnakes.Runtime/Python/IGeneratorIterator.cs
- src/CSnakes.Runtime/Python/Pack.cs
- src/CSnakes.Runtime/Python/PyObject.cs
- src/Integration.Tests/FalseReturns.cs
- src/Profile/Program.cs
This pull request includes several changes across multiple files to improve exception handling, add new test cases, and update type conversion methods. The most important changes include adding exception handling for Python conversions, adding new test cases for collections and dictionaries, and updating type conversion methods to enhance functionality and reliability.
* Updated multiple methods to throw exceptions directly when Python errors occur, improving error reporting and debugging. (`src/CSnakes.Runtime/CPython/Dict.cs`, `src/CSnakes.Runtime/CPython/Import.cs`, `src/CSnakes.Runtime/CPython/List.cs`, `src/CSnakes.Runtime/CPython/Object.cs`, `src/CSnakes.Runtime/CPython/Tuple.cs`, `src/CSnakes.Runtime/CPython/Unicode.cs`) [[1]](diffhunk://#diff-dafeccbc2fa0e3c1f6438cfd0ad4d568be4f648 …
> Compiler conversions

- src/CSnakes.Tests/GeneratedSignatureTests.cs
- src/CSnakes.Tests/TokenizerTests.cs
- src/CSnakes/Parser/PythonParser.TypeDef.cs
- src/CSnakes/Parser/PythonTokenizer.cs
- src/CSnakes/Parser/PythonTokens.cs
- src/CSnakes/Reflection/TypeReflection.cs
> Qualified typenames

- src/CSnakes.sln
This PR fixes the path to the read-me document in Visual Studio solution file otherwise trying to open the file from the Solution Explorer in Visual Studio would give the error: _The document cannot be opened. It has been renamed, deleted or moved._
> Fix path to read-me doc in VS solution file

- src/CSnakes.Runtime/Locators/NuGetLocator.cs
This PR fixes the path that's combined in `NuGetLocator` when `NUGET_PACKAGES` _is_ defined.
On my machine, I have `NUGET_PACKAGES` defined as `C:\dev\packages\nuget` (because I have [package caches located on a Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/#storing-package-cache-on-dev-drive)). When I checked out `main`, which was at commit b39fc5e99f5a721b3db7f077727659d3fcf544df at the time, and ran the tests using:
dotnet test src
all the runtime and integration tests failed due to the error:
System.IO.DirectoryNotFoundException
Python not found at C:\dev\packages\nuget\.nuget\packages\python\3.12.4\tools.
One full example of such an error with the stack trace from a test was:
System.IO.DirectoryNotFoundException
Python not found at …
> Fix NuGet packages override path combination

- docs/examples.md
Found some broken links in [the examples documentation](https://tonybaloney.github.io/CSnakes/examples/) that this PR fixes.
> Fix broken links to examples in docs

- docs/advanced.md
When reading through the [**Calling Python without the Source Generator**](https://tonybaloney.github.io/CSnakes/advanced/#calling-python-without-the-source-generator) section of the documentation, I found it confusing that `ExampleDirectIntegration` did not _technically_ implement `IDisposable`. This PR fixes that to avoid confusing future readers.
> Have direct integration example implement `IDisposable`

- src/CSnakes.Runtime/PackageManagement/PipInstaller.cs
- src/CSnakes.Runtime/PythonEnvironment.cs
* Before
```
info: CSnakes.Runtime.IPythonEnvironment[0]
Setting up Python environment from C:\Users\user\.nuget\packages\python\3.12.4\tools using home of D:\Development\Hackathon-CSnakes\samples\simple\QuickConsoleTest\bin\Debug\net8.0\..\..\..\..\ExamplePythonDependency
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
File D:\Development\Hackathon-CSnakes\samples\simple\QuickConsoleTest\bin\Debug\net8.0\..\..\..\..\ExamplePythonDependency\requirements.txt was found.
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
Using virtual environment at D:\Development\Hackathon-CSnakes\samples\simple\QuickConsoleTest\bin\Debug\net8.0\..\..\..\..\ExamplePythonDependency\.venv to install packages with pip.
info: CSnakes.Runtime.PackageManagement.PipInstaller[0]
Requirement already …
```
> Resolve reported paths

- src/CSnakes.Runtime/PyObjectTypeConverter.cs
- src/CSnakes.Runtime/Python/ICloneable.cs
- src/CSnakes.Runtime/Python/PyDictionary.cs
- src/CSnakes.Runtime/Python/PyList.cs
- src/CSnakes.Runtime/Python/PyObject.cs
- src/Integration.Tests/DictsTests.cs
> Make PyDictionary and PyList convertable back to PyObject without marshalling

- samples/Aspire/CSnakesAspire.ApiService/Program.cs
- src/CSnakes.Runtime/Locators/NuGetLocator.cs
This PR addressed the following two [CS8604](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference) warnings:
A:\CSnakes\main\src\CSnakes.Runtime\Locators\NuGetLocator.cs(15,102): warning CS8604: Possible null reference argument for parameter 'path1' in 'string Path.Combine(string path1, string path2, string path3)'. [A:\CSnakes\main\src\CSnakes.Runtime\CSnakes.Runtime.csproj]
A:\CSnakes\main\samples\Aspire\CSnakesAspire.ApiService\Program.cs(65,88): warning CS8602: Dereference of a possibly null reference. [A:\CSnakes\main\samples\Aspire\CSnakesAspire.ApiService\CSnakesAspire.ApiService.csproj]
that were being flagged during build and also adding a lot of GH Actions annotation noise in PR …
> Fix CS8604 (possible null dereferencing) warnings

- .github/workflows/dotnet-ci.yml
- .github/workflows/dotnet-publish-ci.yml
- .github/workflows/dotnet-publish-gh-packages.yml
- .github/workflows/dotnet-publish-main.yml
- .github/workflows/test-reporting.yml
Some of our CI jobs require access to the `GITHUB_TOKEN`, but the problem is that when they are run from a fork, they don't have permission to do what we need done.
To address this, we need to split the jobs that need permissions out into a new workflow which is run once the triggered workflow completes, since that trigger will run in context of the repo and mean that we can use the `GITHUB_TOKEN`.
Fixes #208
> Supporting forks in CI better

- .devcontainer/devcontainer.json
- .github/workflows/dotnet-ci.yml
- src/CSnakes.Runtime/CPython/Init.cs
- src/Integration.Tests/BufferTests.cs
- src/Integration.Tests/TestDependency.cs
.Net LoadLibrary doesn't offer a way of setting the RTLD flags for Linux.
Python needs global symbols so that further dynamically loaded libraries can resolve symbols from the Python API. 
Our current workaround is to LD_PRELOAD the `libpython` so in the devcontainer and the tests. But this isn't practical for all users.
Fixes #112
> Fix LD_PRELOAD workarounds

- src/CSnakes.Runtime/CPython/List.cs
- src/CSnakes.Runtime/CPython/Tuple.cs
- src/CSnakes.Runtime/Python/Pack.cs
This PR addresses issue #173.
It consolidates tuple and list construction since they shared the bulk of the implementation and both have the same semantics and signatures in CPython (and both, [`PyTuple_SetItem`](https://docs.python.org/3/c-api/tuple.html#c.PyTuple_SetItem) and [`PyList_SetItem`](https://docs.python.org/3/c-api/list.html#c.PyList_SetItem) _steal_ references). It uses a similar approach to the one applied in PR #204. That is, the C APIs for each type are abstracted behind a new interface (with static members only):
```c#
private interface IListOrTupleBuilder
{
static abstract nint New(nint size);
static abstract int SetItemRaw(nint ob, nint pos, nint o);
}
```
Then there's an implementation for tuples (`TupleBuilder`) and another for lists (`ListsBuilder`) that just …
> Pre-allocate list based on source length

- src/CSnakes.Runtime.Tests/Locators/NuGetLocatorTests.cs
This PR fixes a test for `NuGetLocator`, which fails when `NUGET_PACKAGES` is defined, which was the case on my machine. `NuGetLocator` prioritises `NUGET_PACKAGES` if it's defined. The removes the `NUGET_PACKAGES` environment variable when the `USERPROFILE` case is being tested.
The environment variables are saved and restored [before and after each test](https://xunit.net/docs/shared-context#constructor) to factor out the common code.
> Fix test for `NuGetLocator` when `NUGET_PACKAGES` is defined

- src/CSnakes.SourceGeneration/Parser/PythonParser.Constants.cs
- src/CSnakes.SourceGeneration/Parser/Types/PythonConstant.cs
- src/CSnakes.SourceGeneration/Reflection/ArgumentReflection.cs
- src/CSnakes.Tests/TokenizerTests.cs
This PR proposes to refactor `PythonConstant` types into a true union via a class hierarchy where `PythonConstant` becomes an abstract base class and the various types its nested subclasses. This has the following benefits:
- Each subclass has its own clear, simpler and overriding implementation of `ToString` instead of a switch-case previously.
- Each subclass holds its own strong-typed value, e.g. `Value` on `PythonConstant.Integer` is typed as `long` whereas `Value` on `PythonConstant.String` is typed as `string`.
- Each subclass only requires the storage space for its value instead of the sum of all possible values.
- Subclasses like `Bool` and `None` have statically initialised values, which avoids unnecessary allocations.
- `PythonConstant.ConstantType` is no longer needed.
- …
> Refactor `PythonConstant` types into a true union

- src/CSnakes.Runtime/Packaging.targets
- src/Packaging.props
Setting the DevelopmentDependency property will cause the nuspec to have a developmentDependency node in the metadata, which influences how the package is referenced in the consuming projects (see https://github.com/NuGet/NuGet.Client/blob/a41fd92fbbd65fb430e96b11c3277e2c96184474/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L236 for the task entrypoint).
This property would make sense if we were shipping something only for development in the nupkg (like just a source generator or analyzer) but since we're not, we're also shipping a runtime, we don't want the package considered a developmentDependency as that will influence the IncludeAssets and PrivateAssets properties of the package reference.
https://learn.microsoft.com/nuget/reference/nuspec#developmentdependency …
> Fixing how the assemblies are referenced in NuGet

- src/CSnakes.SourceGeneration/PythonStaticGenerator.cs
The source generate implements the `Dispose` method on the implementation of the generated module interfaces:
https://github.com/tonybaloney/CSnakes/blob/bdabf2359e64e81e6069f03a317fd2ab6eb79ac6/src/CSnakes.SourceGeneration/PythonStaticGenerator.cs#L110-L115
Since it doesn't advertise that, the implementation is publicly unreachable and therefore it's impossible to dispose a module and free its memory. This PR fixes that be having module interfaces inherit from `IDisposable`.
> Have generated module interfaces inherit from `IDisposable`

- src/CSnakes.SourceGeneration/Reflection/MethodReflection.cs
This PR proposes to consolidate the redundant `TypeSyntax` patterns in `MethodReflection.FromMethod`.
> Consolidate redundant patterns in `MethodReflection.FromMethod`

- src/CSnakes.Runtime/CPython/Init.cs
- src/Integration.Tests/ArgsTests.cs
- src/Integration.Tests/BasicTests.cs
- src/Integration.Tests/BufferTests.cs
- src/Integration.Tests/DefaultsTests.cs
- src/Integration.Tests/DictsTests.cs
- src/Integration.Tests/ExceptionTests.cs
- src/Integration.Tests/FalseReturns.cs
- src/Integration.Tests/GeneratorTests.cs
- src/Integration.Tests/IntegrationTestBase.cs
- src/Integration.Tests/NoneTests.cs
- src/Integration.Tests/TestDependency.cs
- src/Integration.Tests/TupleTests.cs
This PR fixes #237.
[Apparently](https://stackoverflow.com/a/27225020/6682):
> …calling `Py_Finalize` without holding the global interpreter lock. This is not allowed: the lock must be held for every Python API call, with the single exception of the call that acquires the GIL itself.
This PR acquires the lock prior to calling `Py_Finalize` (but doesn't release it afterwards). Prior to that, it acquires the lock and releases it immediately for the sole purpose of disposing any queued handles before the runtime is finalized:
https://github.com/tonybaloney/CSnakes/blob/c21d30d7e9400d02399d6ba38c1a2787449fe29a/src/CSnakes.Runtime/Python/GIL.cs#L59-L64
The [documentation says](https://tonybaloney.github.io/CSnakes/getting-started/#constructing-a-python-environment-from-c):
> Python …
> Fix GIL acquisition during Python runtime finalization

- src/CSnakes.SourceGeneration/Reflection/TypeReflection.cs
- src/CSnakes.Tests/GeneratedSignatureTests.cs
This was a little hard to parse, somewhat fragile and potentially allocates:
https://github.com/tonybaloney/CSnakes/blob/efd03f84eb3bac396d1bcd5408cdfc31b5b04333/src/CSnakes.SourceGeneration/Reflection/TypeReflection.cs#L23
This PR proposes to use explicit `or` patterns instead for the following benefits (in order of importance):
- Clear and explicit cases of what's accepted, e.g. `"typing.Dict" or "Dict"`
- `typing.` isn't just removed anywhere in the name (always a prefix) to avoid accidental matches
- No new string allocation in case `Replace` the effect of removing the string
I added tests for cases that were previously uncovered to make sure nothing was broken by this PR (unless I got the intent wrong).
> Make type name patterns explicit where `typing.` qualification is optional

- src/CSnakes.Runtime/CPython/Bytes.cs
- src/CSnakes.Runtime/CPython/Call.cs
- src/CSnakes.Runtime/CPython/Dict.cs
- src/CSnakes.Runtime/CPython/Tuple.cs
- src/CSnakes.Runtime/Python/Pack.cs
This PR replaces `Span<>` with `ReadOnlySpan<>` where writing isn't needed to keep the signatures more open and honest.
> Use `ReadOnlySpan` where writing isn't needed

- src/CSnakes.SourceGeneration/CSnakes.SourceGeneration.csproj
- src/CSnakes.SourceGeneration/Properties/launchSettings.json
This PR enables [<kbd>F5</kbd> debugging of the source generator in Visual Studio](https://github.com/dotnet/roslyn-sdk/issues/850) against the integration tests.
> Enable F5 debugging of source generator in Visual Studio

- src/CSnakes.Runtime/PyObjectTypeConverter.Generator.cs
`ConvertToGeneratorIterator` made three calls to [`Type.GetGenericArguments`](https://learn.microsoft.com/en-us/dotnet/api/system.type.getgenericarguments), each of which returns a new and distinct array. This PR optimises it away by make a single call and passing the array directly to [`Type.MakeGenericType`](https://learn.microsoft.com/en-us/dotnet/api/system.type.makegenerictype). It also introduces additional assertions on `destinationType` so it's more clear what's expected on input.
> Optimise generator iterator type instantiation

- src/CSnakes.Runtime/Python/IGeneratorIterator.cs
This PR sets the variance of `IGeneratorIterator<,,>` type parameters, especially for `TYield` to be aligned with `T` of `IEnumerator<out T>`.
> Set variance of `IGeneratorIterator<,,>` type parameters

- src/CSnakes.Runtime/PythonRuntimeException.cs
This PR replaces two calls to get the `__cause__` attribute's value (`exception.GetAttr("__cause__")`) with a single one in order to avoid two hops across the marshalling boundary as well as allocations of the name.
> Get error cause once

- src/Directory.Build.props
> Target .NET 9 if SDK is available

- src/CSnakes.Tests/CSnakes.Tests.csproj
The test project uses types from [Superpower](https://www.nuget.org/packages/Superpower) _directly_ (see [`src/CSnakes.Tests/TokenizerTests.cs`](https://github.com/tonybaloney/CSnakes/blob/048e011b5d70849edb1d0c26fa9b985f8a48f6dc/src/CSnakes.Tests/TokenizerTests.cs#L5) and [`src/CSnakes.Tests/TypeReflectionTests.cs`](https://github.com/tonybaloney/CSnakes/blob/048e011b5d70849edb1d0c26fa9b985f8a48f6dc/src/CSnakes.Tests/TypeReflectionTests.cs#L3)), but doesn't reference it from the test project file. This can throw off some test runners or show up distracting error squiggles in the IDE. This PR adds the missing reference.
> Add missing reference to Superpower in test project

- src/CSnakes.SourceGeneration/Parser/PythonParser.Args.cs
- src/CSnakes.SourceGeneration/Parser/PythonParser.Function.cs
- src/CSnakes.SourceGeneration/Parser/PythonParser.Parameters.cs
- src/CSnakes.SourceGeneration/Parser/PythonParser.TypeDef.cs
- src/CSnakes.Tests/TokenizerTests.cs
- src/CSnakes.Tests/TypeReflectionTests.cs
This PR renames parsers that seem to have been mistakenly named as tokenizers. This helps to avoid confusion when reading and getting familiar with the codebase.
> Rename tokenizers that are actually parsers

- src/CSnakes.Runtime/Locators/RedistributableLocator.cs
The installation lock file path was being computed twice. This PR reuses the previously computed path in `lockfile`.
> Reuse computed installation lock file path

- src/CSnakes.Runtime/Locators/RedistributableLocator.cs
`RedistributableLocator` currently installs to [`Environment.SpecialFolder.ApplicationData`][SpecialFolder:fields], but [`Environment.GetFolderPath`] can return an empty string for this on some systems and therefore the installation fails. For example, testing `RedistributablePython.Tests` on the .NET SDK 9 docker image:
```sh
docker run --rm mcr.microsoft.com/dotnet/sdk:9.0 bash -ec '
cat /etc/os-release
git clone --depth 1 --branch v1.0.23 https://github.com/tonybaloney/CSnakes.git csnakes
cd csnakes
dotnet test -f net9.0 --tl:off src/RedistributablePython.Tests'
```
fails:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/" …
> Fix `RedistributableLocator` install when special folder is missing

- src/CSnakes.Runtime/Locators/RedistributableLocator.cs
This PR suggests to replace installation lock file with the use of a named [`Mutex`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.mutex.-ctor?view=net-9.0#system-threading-mutex-ctor(system-boolean-system-string)), which requires less code (no polling with sleeps and lock file management), supports timing out, has cross-platform support and doesn't suffer from race conditions of file operations (which require more care). Moreover, a process that crashes and whose thread owned the mutex can signal [abandonment](https://github.com/dotnet/runtime/blob/9d5a6a9aa463d6d10b0b0ba6d5982cc82f363dc3/src/coreclr/pal/src/include/pal/mutex.hpp#L111-L116) to others so they can acquire the lock.
Incidentally, the [`Mutex` implementation on some non-Windows platforms also uses a lock …
> Use system mutex in `RedistributableLocator` during installation

- src/CSnakes.Runtime/PackageManagement/PipInstaller.cs
- src/CSnakes.Runtime/PackageManagement/UVInstaller.cs
The `PATH` path separator in the package installers was hard-coded to `;`, which is only valid for Windows. On Linux and macOS, it's usually `:`. This PR fixes the issue by using [`Path.PathSeparator`], which returns the correct path separator for the host OS.
[`Path.PathSeparator`]: https://learn.microsoft.com/en-us/dotnet/api/system.io.path.pathseparator
> Fix `PATH` path separator in package installers

- src/CSnakes.Runtime/Locators/RedistributableLocator.cs
The use of [`HttpClient.GetAsync` ](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getasync?view=net-9.0#system-net-http-httpclient-getasync(system-string)) to download the Python redistributable in `RedistributableLocator` causes 
the _entire_ response content to be buffered to memory before being written to disk. Just stepping over the following line in the debugger:
https://github.com/tonybaloney/CSnakes/blob/de05da4d0a40477bd3f69a6c1388f7e408617066/src/CSnakes.Runtime/Locators/RedistributableLocator.cs#L166
shows the memory spike (over 2,600 objects and tens of MBs allocated):
<p><img width="50%" height="50%" src="https://github.com/user-attachments/assets/b320fece-98ac-4ee9-be10-e0818b3ecc32"></p>
If one examines the heap for byte arrays, we find a 41.6MB …
> Reduce memory load of redistributable download

- src/CSnakes.Runtime.Tests/Python/RunTests.cs
- src/CSnakes.Runtime/CPython/Run.cs
- src/CSnakes.Runtime/IPythonEnvironment.cs
- src/CSnakes.Runtime/PythonEnvironment.cs
- src/CSnakes.Runtime/PythonRunString.cs
Implements #290 
Adds two different types of API:
- IPythonEnvironment.ExecuteExpression which takes a simple expression (`1+1`) and returns the result
- IPythonEnvironment.Execute which takes a string, typically multiple lines
> Allow users to run Python code from a string

- src/CSnakes.Runtime/Locators/RedistributableLocator.cs
This PR configures awaits in `RedistributableLocator` to continue on any thread. This will help to avoid deadlocks in UI applications (and hopefully fixes #322). Without the `.ConfigureAwait(false)`, the `await` points will try and continue on the captured context and the UI event loop thread in a desktop application. If the synchronous `LocatePython` method gets called on a UI thread, there's a good chance it will deadlock the application when initiating the download.
> Configure awaits in `RedistributableLocator` to continue on any thread

- src/CSnakes.Runtime/PackageManagement/PipInstaller.cs
The type definition doesn't match the nullability requirements and thus a warning.
> Fix warning

- src/CSnakes.Runtime.Tests/Python/GILTests.cs
- src/CSnakes.Runtime/Python/GIL.cs
If `GIL.Disposed` is called more times than `GIL.Acquire` then a fatal error is reported
Exit code is -1073740791 (Fatal Python error: PyEval_SaveThread: the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized
Current thread 0x000088dc (most recent call first):
<no Python frame>
Thread 0x000088cc (most recent call first):
<no Python frame>)
This PR fixes the problem by making `GIL.Dispose` idempotent once the recursion count falls to 0 and the GIL has been previously released.
> Make GIL disposal idempotent once disposed

- src/CSnakes.Runtime.Tests/Python/GILTests.cs
This PR adds some basic tests for GIL management. The tests ensure that the GIL is acquired and released correctly, and that its state is maintained properly across different scenarios like nested scopes and each thread maintaining its own local state.
---
See also: https://github.com/tonybaloney/CSnakes/pull/372#issuecomment-2727137134
> Add basic tests to exercise GIL management

- src/CSnakes.Runtime/CSnakes.Runtime.csproj
- src/Directory.Packages.props
Tony thank you for the excellent talk today with Hanselman I am in love with this library!
I noticed when digging through my dependency graph that it was still pulling in RC2 .NET 9 stuff as well as System.Text.Json but STJ is included in the runtime when your target framework moniker is set at 8 or 9.
> Cleanup dependencies now that .NET 9 has hit RTM

- src/Conda.Tests/CondaTestBase.cs
This PR changes `CondaTestBase.cs` to look for the conda folder in the home directory instead of the working directory.
This change makes these tests runnable on my OSX machine.
> More rebust search for conda source folder

- src/CSnakes.Runtime/ServiceCollectionExtensions.cs
This PR closes #406 by:
- adding a new `FromRedistributable` that doesn't have any version selection argument and defaults to 3.12.
- updating existing overloads to require the version argument to avoid overload ambiguity
The new `FromRedistributable` also doesn't have a `freeThreaded` argument to avoid confusion since it wouldn't make sense for the currently defaulted version 3.12.
Another way to solve this problem is to simply not add a new overload and always require the version number explicitly, which I think is better but let me know your preference, @tonybaloney.
> Fix `FromRedistributable` overload resolution error

- src/CSnakes.SourceGeneration/PythonStaticGenerator.cs
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_args.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_args_underscore.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_basic.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_buffer.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_coroutines.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_defaults.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_dependency.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_dicts.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_exceptions.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_false_returns.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_generators.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_keywords.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_none.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_pybind11.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_reload.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_reserved.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_sys.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_tuples.approved.txt
- src/Integration.Tests/ArgsTests.cs
- src/Integration.Tests/BufferTests.cs
- src/Integration.Tests/CoroutineTests.cs
- src/Integration.Tests/DictsTests.cs
- src/Integration.Tests/ExceptionTests.cs
- src/Integration.Tests/FalseReturns.cs
- src/Integration.Tests/GeneratorTests.cs
- src/Integration.Tests/Integration.Tests.csproj
- src/Integration.Tests/IntegrationTestBase.cs
- src/Integration.Tests/ReloadTests.cs
- src/Integration.Tests/TupleTests.cs
This PR fixes #408.
This is now validated through the integration tests where implicit usings is disabled. This also means that imports that were implicitly present previously had to be added explicitly to test project files where necessary.
> Add missing `System.Threading.Tasks` import in generated code

- src/CSnakes.Runtime.Tests/Converter/IntConverterTest.cs
- src/CSnakes.Runtime/CPython/Long.cs
- src/CSnakes.Runtime/Python/Interns/ImmortalSmallInteger.cs
- src/CSnakes.Runtime/Python/PyObject.cs
`PyObject.As` for `int`/`Int32` ends up calling [`PyLong_AsLong`](https://docs.python.org/3/c-api/long.html#c.PyLong_AsLong), which returns a `long`, but a `long` has different widths on different 64-bit platforms. For example, Windows uses the LLP64 data model where a `long` is 32 bits wide and Linux uses LP64 where a `long` is 64 bits wide. This PR fixes the problem by using [`PyLong_AsLongLong`](https://docs.python.org/3/c-api/long.html#c.PyLong_AsLongLong) instead since it returns `long long` and that's consistently 64 bits wide across LLP64 and LP64 data models. On the .NET side, `long long` pops up as `Int64`, which is then converted to `int`/`Int32` with an overflow check. This change makes the behaviour consistent.
This fix also indirectly addresses another (more surprising) …
> Fix `PyObject.As` for `int` on LP64 & LLP64

- src/CSnakes.Runtime.Tests/Python/ImmortalTests.cs
- src/CSnakes.Runtime/Python/PyObject.cs
`PyObject.From` would return immortals for 0, 1 and -1 as long as they were `int` values. It would allocate a new `PyObject` if 0, 1 and -1 were typed as `long` or `BigInteger`. This PR extends `PyObject.From` to also consider `long` and `BigInteger` values. Tests have been extended for both cases (refactored to break out each case and consolidate all duplication). At the same time, all immortals ard considered for returning outside of taking the GIL, which I believe is safe. `PyObject.From` takes the GIL when it's exhausted those optimisations or immortal cases.
---
PS I believe some of the tests are failing on Linux ARM and macOS due to the problem that #415 fixes.
> Return immortals from `PyObject.From` for `long` + `BigInteger`

- src/CSnakes.Runtime/Python/GeneratorIterator.cs
- src/Integration.Tests/GeneratorTests.cs
Per the [**Remarks** section](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?view=net-9.0#remarks) of the [`IDisposable.Dispose`](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?view=net-9.0) documentation, an object disposal should be idempotent:
> If an object's [`Dispose`](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?view=net-9.0) method is called more than once, the object must ignore all calls after the first one.
However, `GeneratorIterator.Dispose` throws `ObjectDisposedException` if the object was previously disposed. This PR removes the check and throw so that disposal become idempotent.
> Make generator iterator disposal idempotent

- docs/async_support.md
- src/CSnakes.Runtime/CPython/Coroutine.cs
- src/CSnakes.Runtime/Python/Coroutine.cs
- src/CSnakes.Runtime/Python/ICoroutine.cs
This PR fixes `CancellationToken` parameters in member related to coroutines to be non-nullable, which is more standard. The documentation for [`CancellationToken.None`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.none?view=net-9.0) has more on this:
> The cancellation token returned by this property cannot be canceled; that is, its [`CanBeCanceled`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.canbecanceled?view=net-9.0) property is `false`.
>
> You can also use the C# [`default(CancellationToken)`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/default) statement to create an empty cancellation token.
>
> Two empty cancellation tokens are always equal.
Making a `CancellationToken` …
> Fix `CancellationToken` parameters to be non-nullable

- src/CSnakes.SourceGeneration/Parser/PythonParser.Function.cs
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_basic.approved.txt
- src/Integration.Tests/python/test_basic.py
This PR skips code generation of C# proxies for Python functions whose name starts with an underscore (`_`). As per [PEP 8](https://peps.python.org/pep-0008/), these are conventionally considered _internal_:
> - `_single_leading_underscore`: weak “internal use” indicator. E.g. `from M import *` does not import objects whose names start with an underscore.
> Skip C# proxies for underscored functions

- docs/buffers.md
- src/CSnakes.SourceGeneration/Reflection/TypeReflection.cs
- src/CSnakes.SourceGeneration/ResultConversionCodeGenerator.cs
This PR is a follow-up to: https://github.com/tonybaloney/CSnakes/pull/413#discussion_r2053377528
> Remove recognition `typing.Buffer` that never was

- src/CSnakes.Runtime/Python/Coroutine.cs
- src/CSnakes.Runtime/Python/ICoroutine.cs
This PR takes care of the following warnings:
```
A:\CSnakes\main\src\Profile\obj\Debug\net8.0\CSnakes.SourceGeneration\CSnakes.PythonStaticGenerator\AsyncBenchmarks.py.cs(88,24): warning CS8619: Nullability of reference types in value of type 'Task<PyObject?>' doesn't match target type 'Task<PyObject>'.
A:\CSnakes\main\src\Integration.Tests\obj\Debug\net9.0\generated\CSnakes.SourceGeneration\CSnakes.PythonStaticGenerator\TestCoroutines.py.cs(122,24): warning CS8619: Nullability of reference types in value of type 'Task<PyObject?>' doesn't match target type 'Task<PyObject>'.
```
There's no need for `TYield` to have the nullability specifier `?`.
> Make coroutine task result be just `TYield`

- src/CSnakes.Runtime.Tests/Python/GILTests.cs
- src/CSnakes.Runtime/Python/GIL.cs
This PR proposes to return the GIL acquisition as a `ref struct` called ~~`AcquiredLock`~~ `GIL.Lock`. The semantics are as before except the `ref struct` ensures that the lock cannot escape to the heap easily when state machines get formed indirectly in code using `async`/`await` and `yield`. Either way, it prevents the code from compiling if the code after a `yield` or `await` could resume on a different thread than on which the lock was acquired.
The following code was possible up to now:
```c#
static IEnumerable<int> Test()
{
using (GIL.Acquire())
yield return 42;
}
static async Task<int> TestAsync()
{
using (GIL.Acquire())
await Task.Yield();
return 42;
}
```
but will produce error CS4007 after this PR:
error CS4007: Instance of type 'CSnakes.Runtime.Python.GIL.Lock' cannot be …
> Make GIL acquisition a `ref struct`

- src/CSnakes.Runtime/Python/Coroutine.cs
- src/CSnakes.SourceGeneration/PythonStaticGenerator.cs
- src/CSnakes.SourceGeneration/Reflection/MethodReflection.cs
- src/CSnakes.SourceGeneration/ResultConversionCodeGenerator.cs
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_args.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_args_underscore.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_basic.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_buffer.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_coroutines.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_defaults.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_dependency.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_dicts.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_exceptions.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_false_returns.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_generators.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_keywords.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_none.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_pybind11.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_reload.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_reserved.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_sys.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_tuples.approved.txt
- src/Integration.Tests/CoroutineTests.cs
- src/Integration.Tests/python/test_coroutines.py
This PR closes #353.
It adds a test to exercise the cancellation, which surfaced a bug in `Coroutine.AsTask` and is fixed by transforming a `CancelledError` from Python into the task being treated as cancelled on the .NET side. Otherwise the task would fail with a `PythonInvocationException` on being cancelled.
I've also gone ahead and removed special-casing of coroutine conversion to `Task` in `MethodReflection.FromMethod` (adding further to #377) so now it's done entirely within `CoroutineConversionGenerator`, which is just another (new) `IResultConversionCodeGenerator` implementation.
> Add `CancellationToken` parameter to generated async methods

- src/Profile/Program.cs
PR #419 refactored benchmarks into two suites, but it's no longer possible to select other benchmarks than `MarshallingBenchmarks` from the CLI. For example, running:
dotnet run --project src/Profile -c Release -f net9.0 -- --list tree
produces the following output and ends in an error:
Using launch settings from src\Profile\Properties\launchSettings.json...
Profile
└─MarshallingBenchmarks
├─ComplexReturn
├─ComplexReturnLazy
├─FunctionReturnsList
├─FunctionTakesList
├─FunctionTakesDictionary
├─FunctionReturnsDictionary
├─FunctionReturnsTuple
├─FunctionTakesTuple
├─FunctionTakesValueTypes
└─EmptyFunction
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
at System.Linq.ThrowHelper.ThrowNoElementsException()
at …
> Use `BenchmarkSwitcher` in profiling project

- src/Profile/BaseBenchmark.cs
This PR proposed to add the memory diagnoser for benchmarks since it's generally useful to measure memory impact in size vs speed trade-offs. For example, this adds the `Allocated` below:
| Method        | Mean     | Error    | StdDev   | Allocated |
|-------------- |---------:|---------:|---------:|----------:|
| AsyncFunction | 15.54 ms | 0.188 ms | 0.176 ms |     777 B |
> Add memory diagnoser to benchmarks

- src/CSnakes.Runtime.Tests/Python/PyDictionaryTests.cs
- src/CSnakes.Runtime.Tests/Python/PyListTests.cs
- src/CSnakes.Runtime/Python/PyDictionary.cs
- src/CSnakes.Runtime/Python/PyEnumerable.cs
- src/CSnakes.Runtime/Python/PyList.cs
- src/CSnakes.Runtime/Python/PyObject.cs
- src/Integration.Tests/PyObjectTests.cs
This PR fixes the semantics of `PyObject.AsEnumerable<T>()`, which has a number of problems.
`PyEnumerable` was declared as an enumerable _and_ an enumerator at the same time:
https://github.com/tonybaloney/CSnakes/blob/07e4e2171d88deac63cf3974e7bef19721e5a915/src/CSnakes.Runtime/Python/PyEnumerable.cs#L6
The `GetEnumerator` would just return `this`:
https://github.com/tonybaloney/CSnakes/blob/07e4e2171d88deac63cf3974e7bef19721e5a915/src/CSnakes.Runtime/Python/PyEnumerable.cs#L26
However, an [`IEnumerable<T>.GetEnumerator`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1.getenumerator) implementation should return a new enumerator on each call such that each enumerator represents an _independent_ iteration through the sequence. If the same enumerator …
> Fix `AsEnumerable` semantics

- src/CSnakes.Runtime.Tests/Python/PyObjectTests.cs
- src/CSnakes.Runtime/CPython/Object.cs
- src/CSnakes.Runtime/Python/PyObject.cs
This PR adds support for Python's truthy-falsy behavior to the `PyObject` class in CSnakes. This enhancement allows C# code to use Python objects directly in boolean contexts (conditionals, logical operations) in a way that mimics Python's behavior.
In Python, objects can be evaluated in boolean contexts, following specific rules for truthiness:
- Objects like empty collections (`[]`, `{}`, `()`), zero (`0`), `None`, and empty strings (`""`) evaluate to `False`
- Non-empty collections, non-zero numbers, non-empty strings, and most other objects evaluate to `True`
This PR implements this behavior for CSnakes, allowing seamless integration of Python's boolean semantics in C#.
The implementation adds:
1. Three operator overloads in `PyObject`:
- `operator true` - Determines if a Python …
> Implement truthy-falsy for `PyObject`

- src/CSnakes.Runtime/CPython/Coroutine.cs
- src/CSnakes.Runtime/CPython/EventLoop.cs
- src/CSnakes.Runtime/CPython/Init.cs
- src/CSnakes.Runtime/Python/Coroutine.cs
- src/Profile/AsyncBenchmarks.cs
- src/Profile/async_benchmarks.py
This PR refactors the Python coroutine handling in CSnakes to use a single shared event loop _and_ thread for all coroutines instead of creating a new one for each coroutine operation and per thread. The change significantly improves performance and operational behaviour (more on that later), especially when running multiple coroutines concurrently.
The refactored implementation:
- uses a single, lazily-initialized, shared event loop that runs continuously.
- implements a message queue pattern for scheduling coroutines on the shared loop.
- runs the event loop on a dedicated background thread via `Task.Run`.
- supports cancellation, failure and successful completion of tasks.
1. **Shared Event Loop**
- A singleton `EventLoop` instance is created on demand and maintained until disposed …
> Refactor to use a single event loop for coroutines

- src/CSnakes.Runtime.Tests/Python/ImportTests.cs
- src/CSnakes.Runtime.Tests/Python/PyObjectTests.cs
- src/CSnakes.Runtime/Python/PyObject.cs
This PR proposes to replace the generic `PyObject.From<T>` method with multiple type-specific overloads. The change improves code readability, maintainability, and performance by providing dedicated conversion paths for each supported type.
The previous implementation used a single generic method with a large switch statement that handled many different types. This approach had several drawbacks:
- It obscured which types were actually supported
- The single method contained complex branching logic (possibly hurting [CPU branch prediction](https://en.wikipedia.org/wiki/Branch_predictor))
The new design:
- Provides dedicated overloads for each supported type (bool, long, double, string, etc.)
- Uses more idiomatic C# method overloading
- Makes supported types explicit in the API surface
- …
> Improve performance with per-type overloads for `PyObject.From`

- src/CSnakes.Runtime/CPython/Buffer.cs
- src/CSnakes.Runtime/Python/PyBuffer.cs
This PR optimizes the buffer initialisation by replacing the by-value buffer creation with a more efficient by-reference approach. It significantly reduces assembly instructions and improves performance.
The primary design change converts the buffer handling from a return-value pattern to an out-parameter pattern:
1. Modified `GetBuffer` method signature from returning a `Py_buffer` to using an `out` parameter
2. Changed the P/Invoke signature of `PyObject_GetBuffer` to use `out` parameter instead of a pointer
3. Updated the caller in `PyBuffer.cs` to use the new pattern
This shift from by-value to by-reference parameter handling eliminates unnecessary memory operations and structure copying.
Before the changes, the `GetBuffer` method would:
1. Create a local `Py_buffer` on the stack
2. …
> Use by-ref initialisation of `Py_buffer`

- src/CSnakes.Runtime/CPython/Buffer.cs
- src/CSnakes.Runtime/Python/PyBuffer.cs
This PR removes the need to mark the `PyBuffer` constructor as unsafe.
> Make `PyBuffer` constructor safe

- src/CSnakes.Runtime/Python/IPyBuffer.cs
- src/CSnakes.Runtime/Python/PyBuffer.cs
- src/Integration.Tests/BufferTests.cs
This PR fixes memory leaks from acquiring a buffer by making `IPyBuffer` inherit from `IDisposable`.
Up unit now, there was no way for user code to dispose an `IPyBuffer` object and so all memory backing a buffer leaks.
The leak can be observed with the following code:
```diff
diff --git a/src/Integration.Tests/BufferTests.cs b/src/Integration.Tests/BufferTests.cs
index 18cdbe4..795cc30 100644
--- a/src/Integration.Tests/BufferTests.cs
+++ b/src/Integration.Tests/BufferTests.cs
@@ -1,6 +1,7 @@
+using CSnakes.Runtime.Python;
using System;
using System.Collections.Generic;
-using CSnakes.Runtime.Python;
+using System.Diagnostics;
using Xunit;
namespace Integration.Tests;
@@ -177,14 +178,23 @@ public class BufferTests(PythonEnvironmentFixture fixture) : IntegrationTestBase
public void …
```
> Fix leaks by making `IPyBuffer` disposable

- .github/workflows/dotnet-ci.yml
- src/Integration.Tests/python/test_buffer.py
- src/Integration.Tests/python/test_coroutines.py
- src/Integration.Tests/python/test_dicts.py
- src/Integration.Tests/python/test_false_returns.py
- src/Integration.Tests/python/test_pybind11.py
Validate that the type annotations in our tests are actually correct.
Would have stopped #480
> Run type checkers in CI

- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_buffer.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_dicts.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_false_returns.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_pybind11.approved.txt
This PR fixes the reload hashes in test snapshots that were not updated as part of PR #480 and therefore was [breaking `main` branch build](https://github.com/tonybaloney/CSnakes/actions/runs/15388631928) (at commit 17fd40f166d2100469f93a73fb5ecdf0c77522ba).
> Fix reload hashes in test snapshots

- src/CSnakes.SourceGeneration/Reflection/MethodReflection.cs
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_args_underscore.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_basic.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_keywords.approved.txt
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_reserved.approved.txt
This PR was forked from PR #488.
It simply discards the result of a Python function that returns `None` (mapped to `void` in C#) instead of disposing it because [`None` is immortal](https://github.com/tonybaloney/CSnakes/blob/490ab6adc39fbdb00585cc9c6eec57a4cd1f2cd6/src/CSnakes.Runtime/Python/Interns/PyNoneObject.cs#L5) and [disposing it has no effect](https://github.com/tonybaloney/CSnakes/blob/490ab6adc39fbdb00585cc9c6eec57a4cd1f2cd6/src/CSnakes.Runtime/Python/Interns/ImmortalPyObject.cs#L12-L15). Discarding helps to remove any costs associated with try-finally setup.
> Discard result when function returns `None`

- .github/workflows/dotnet-ci.yml
- docs/environments.md
- src/CSnakes.Runtime/PackageManagement/IPythonPackageInstaller.cs
- src/CSnakes.Runtime/PackageManagement/PipInstaller.cs
- src/CSnakes.Runtime/PackageManagement/UVInstaller.cs
- src/CSnakes.Runtime/PythonEnvironment.cs
- src/CSnakes.Runtime/ServiceCollectionExtensions.cs
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_dependency.approved.txt
- src/Integration.Tests/IntegrationTestBase.cs
- src/Integration.Tests/TestDependency.cs
- src/Integration.Tests/python/test_dependency.py
Refactor the installer APIs so that you can install a `requirements.txt` file, _or_ a list of packages.
Also refactors the IPythonPackageInstaller so that environment manager comes from the DI at setup time
> Enable simple runtime package installation

- samples/Aspire/python/weather.py
This PR fixes the optionality of the arguments for the weather demo. It was forked from PR #456 where @buvinghausen contributed the patch, but which could be separated.
> Fix optionality of weather demo arguments

- docs/reference.md
This is a follow-up PR to #502 that mentions the new support in the documentation.
> Mention `T | None` in support types doc

- src/CSnakes.SourceGeneration/Reflection/ArgumentReflection.cs
- src/CSnakes.Tests/GeneratedSignatureTests.cs
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_defaults.approved.txt
- src/Integration.Tests/python/test_defaults.py
Fixes #512 
Catch default values for parameters which have no standard conversion.
This does not catch invalid conversions, e.g. `def foo(x: str = 42) -> int`.
> Don't generate parameter defaults on unsupported types

- src/CSnakes.SourceGeneration/Parser/PythonParser.TypeDef.cs
- src/CSnakes.SourceGeneration/Parser/Types/PythonTypeSpec.cs
- src/CSnakes.Tests/GeneratedSignatureTests.cs
- src/CSnakes.Tests/TokenizerTests.cs
- src/CSnakes.Tests/TypeReflectionTests.cs
This PR goes part of the way to implement #24 
It implements the tokenization and parsing of basic PEP586 literals including mixed types.
The reflected type will still be `PyObject`. A second follow-up PR will look at the constants and if they are all the same type, add a type conversion or use an enum.
Currently, any type signature with `Literal[1, "two", 3.0]` will fail to parse and the function won't be included at all in the generated Class.
> Allow parsing of PEP586 Literal types

- src/CSnakes.Tests/CSnakes.Tests.csproj
- src/CSnakes.Tests/PythonStaticGeneratorTests.cs
This PR reverts changes from PR #521 and #280 and instead uses the [`TestTfmsInParallel` settings (introduced with .NET 9 SDK)](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/sdk#run-tests-in-parallel) to disable parallel testing across target frameworks.
The hacks in PR #521 and #280 were incorrect because the problem wasn't potential flakiness of approval tests on ARM, but rather inherent to the fact that tests for each target framework (.NET 8 and 9) were running in parallel and caused race conditions for _received files_ on disk. The symptoms would manifest as the received file disappearing, violating locks or seeing an empty file. As an example of this, if a .NET 8 approval test case passed, it would delete the received file, but if the same test case were running …
> Run approval tests sequentially to prevent file race conditions

- src/CSnakes.SourceGeneration/Parser/PythonParser.TypeDef.cs
- src/CSnakes.SourceGeneration/Parser/Types/PythonTypeSpec.cs
- src/CSnakes.Tests/ParameterListParserTests.cs
- src/CSnakes.Tests/TypeReflectionTests.cs
This PR closes #520. It significantly improves the Python type parser by implementing comprehensive support for Union types, including both the traditional `Union[...]` syntax and modern pipe syntax (`A | B`). The changes introduce type normalization, de-duplication, and optimization strategies.
It should help with efforts like #499.
The implementation is optimized for up to 3 unions and then takes a slower path for more esoteric expressions of a Union that requires normalization of sorts.
The core design philosophy shifts from treating Union types as edge cases to handling them as first-class citizens in the type system.
1. **Unified Type Parsing**: Consolidates the handling of different type syntaxes (None, Union, pipe syntax) into a single, coherent parsing strategy
2. …
> Add support for `Union` types, including pipe syntax

- samples/Aspire/CSnakesAspire.ApiService/CSnakesAspire.ApiService.csproj
- samples/Aspire/CSnakesAspire.ApiService/Program.cs
- samples/Aspire/CSnakesAspire.AppHost/CSnakesAspire.AppHost.csproj
- samples/Aspire/CSnakesAspire.ServiceDefaults/CSnakesAspire.ServiceDefaults.csproj
- samples/Aspire/CSnakesAspire.ServiceDefaults/Extensions.cs
- samples/Aspire/CSnakesAspire.Web/CSnakesAspire.Web.csproj
- samples/Aspire/CSnakesAspire.Web/Program.cs
- samples/Aspire/python/weather.py
Removed all references to System.Text.Json as it is provided by the .net9.0 runtime
Removed unused references from weather.py
Removed all references that are inherited from project dependencies
Changed all dependences to floating at the minor level but Aspire dependencies float at the patch level
The reason for the latter is the AppHost project must have the Aspire SDK listed in full ex: 9.3.0 and so we only want patches within that release cycle.
> Upgrade to Aspire 9.3 and dependency cleanup

- src/CSnakes.Runtime/Python/GIL.cs
- src/CSnakes.Runtime/Python/PyBuffer.cs
- src/Integration.Tests/BufferTests.cs
This PR introduces a finalizer for `PyBuffer` to ensure that the native buffer is released if not explicitly disposed via its `IDisposable.Dispose` implementation. Without this, the buffer will leak.
Just like `PyObject`, if the GIL is not already acquired during finalization, the actual release is queued until the GIL is acquired and released next time.
Tests have been added to ensure that attempts to use a `PyBuffer` object once it's been disposed results in `ObjectDisposedException` being thrown.
---
PS This PR is forked from PR #505.
> Add `PyBuffer` finalizer to prevent potential leaks

- src/CSnakes.SourceGeneration/Parser/PythonParser.Function.cs
- src/CSnakes.Tests/TokenizerTests.cs
Fixes the removal of trailing comments logic to not use # markers inside lines.
Uses the token list to determine an accurate marker of the last token in the line.
> Address # in line being removed as comment

- src/CSnakes.SourceGeneration/Parser/PythonParser.TypeDef.cs
- src/CSnakes.SourceGeneration/Reflection/MethodReflection.cs
- src/CSnakes.Tests/GeneratedSignatureTests.cs
Fixes #541 
```python
def foo(a: int, b: int = 2, *, kw: str) -> None:
pass
```
Something like this would fail to compile.
> Fix bug when positional args with defaults are following by a * then a keyword-only parameter without a default

- src/CSnakes.Runtime/PublicAPI/net8.0/PublicAPI.Shipped.txt
- src/CSnakes.Runtime/PublicAPI/net9.0/PublicAPI.Shipped.txt
- src/Directory.Build.props
Public API control was added with PR #530 to help with #453, but unfortunately, the tracking was getting outdated since warnings were being ignored. The following setting in `Directory.Build.props` is actually incorrect as it doesn't have the desired effect of treating warnings as error:
https://github.com/tonybaloney/CSnakes/blob/7a19e9ad4244219409dbe4a59bde50c0aa1927bc/src/Directory.Build.props#L7
The setting is called [`TreatWarningsAsErrors`](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#treatwarningsaserrors).
In this PR, most warnings from **Microsoft.CodeAnalysis.PublicApiAnalyzers** are configured as errors so that the tracking is kept fresh and breaking changes can be caught when introduced. It also updates the shipped API …
> Fix shipped API list

- src/CSnakes.sln
Some `*.props` and `*.targets` were present in the solution while others not. This PR fixes that by adding the missing ones.
> Add `Directory.Build.*` & `Packaging.*` to solution

- src/CSnakes.Runtime/Locators/RedistributableLocator.cs
The redistributable packages have complex/invalid symlinks in the directory tree. This lowers the error level to warning since they can be ignored
> Lower symlink error to warnings

- src/Profile/Profile.csproj
This is a follow-up to PR #649 that removes the unused python package reference from the **Profile** project.
> Remove unused python reference from "Profile" project

- src/CSnakes.Runtime/Locators/RedistributableLocator.cs
- src/CSnakes.Runtime/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/CSnakes.Runtime/PublicAPI/net9.0/PublicAPI.Unshipped.txt
- src/CSnakes.Runtime/ServiceCollectionExtensions.cs
This PR propose to refactor the enum-based + attributes + reflection to represent redistributable Python versions with a reflection-free and static one. It should be faster, more type-safe and friendlier for Native AOT scenarios.
Since this is a **breaking change** (that should be mostly source-compatible), it should be noted for #631.
> Refactor `RedistributablePythonVersion` to remove reflection

- src/CSnakes.SourceGeneration/CSnakes.SourceGeneration.csproj
- src/CSnakes.SourceGeneration/Parser/PythonParser.Constants.cs
- src/CSnakes.SourceGeneration/Parser/PythonParser.Function.cs
- src/CSnakes.SourceGeneration/Parser/PythonParser.Parameters.cs
- src/CSnakes.SourceGeneration/Parser/PythonParser.TypeDef.cs
- src/CSnakes.SourceGeneration/Parser/PythonParser.cs
- src/CSnakes.Tests/TokenizerTests.cs
This PR addressed the following warnings in the **CSnakes.SourceGeneration** project:
src\CSnakes.SourceGeneration\Parser\PythonParser.Function.cs(16,29): warning CS8603: Possible null reference return.
src\CSnakes.SourceGeneration\Parser\PythonParser.Function.cs(18,43): warning CS8604: Possible null reference argument for parameter 'second' in 'TokenListParser<PythonToken, PythonTypeSpec> Combinators.IgnoreThen<PythonToken, Token<PythonToken>, PythonTypeSpec>(TokenListParser<PythonToken, Token<PythonToken>> first, TokenListParser<PythonToken, PythonTypeSpec> second)'.
src\CSnakes.SourceGeneration\Parser\PythonParser.Parameters.cs(14,44): warning CS8604: Possible null reference argument for parameter 'parser' in 'TokenListParser<PythonToken, PythonTypeSpec?> …
> Fix CS8603 + CS8604 warnings in setup of parsers

- src/CSnakes.Runtime.Tests/Converter/ConverterTestBase.cs
This pull request makes a minor adjustment to the test discovery behavior in the `ConverterTestBase` test classes. The key change is the addition of the `DisableDiscoveryEnumeration = true` parameter to the `[MemberData]` attribute, which can improve test performance and reliability in certain scenarios.
Test attribute adjustments:
* Added `DisableDiscoveryEnumeration = true` to the `[MemberData]` attribute in `RoundtripViaAs` and `RoundtripViaImport` test methods in `ConverterTestBase`. This can help avoid issues with test discovery and enumeration, especially for large or complex data sets. [[1]](diffhunk://#diff-c8e299876bd053d2fc73b953d70bbe9d2c9693dc0add9dbb90f5b0be31d6e5deL25-R25) [[2]](diffhunk://#diff-c8e299876bd053d2fc73b953d70bbe9d2c9693dc0add9dbb90f5b0be31d6e5deL36-R36) …
> Add DisableDiscoveryEnumeration to MemberData attributes in ConverterTestBase

- src/CSnakes.Runtime/Locators/RedistributableLocator.cs
Per latest release:
https://github.com/astral-sh/python-build-standalone/releases/tag/20250902
Bumping 3.14 to rc2
Bumping 3.13.6 to 3.13.7
Tested locally
> Update redistributable Python to 3.14.0rc2 and 3.13.7

- src/CSnakes.Runtime/PythonLogger.cs
This removes the `NoneValueImporter<,>` that was private to the logger in favour of reusing `OptionalValueImporter<,>` that was added with PR #689.
> Reuse optional value importer in logger

- src/CSnakes.Runtime/PythonLogger.cs
- src/CSnakes.Tests/PythonStaticGeneratorTests/FormatClassFromMethods.test_logging.approved.txt
- src/Integration.Tests/LoggingTests.cs
- src/Integration.Tests/python/test_logging.py
This PR enhances the Python logging bridge to track and report dropped messages instead of silently losing them. Previously, when the logging queue overflowed, messages would be silently lost. Now the system provides clear indication of how many messages were dropped, enabling better monitoring and debugging.
The generator now yields a 4-tuple instead of a 3-tuple:
```python
```
The drop count represents messages lost since the last successful yield, and is reset to zero after being reported.
The bridge now processes drop counts and issues debug messages when drops are detected.
`test_many_entries(count: int)` replaces the hardcoded `test_fifty_entries()` to allow configurable test scenarios.
**Overflow Test**: A comprehensive test that deliberately creates a slow logger scenario to …
> Log & test logging queue buffer overflow

- src/CSnakes.Runtime/PublicAPI/net8.0/PublicAPI.Unshipped.txt
- src/CSnakes.Runtime/PublicAPI/net9.0/PublicAPI.Unshipped.txt
- src/CSnakes.Runtime/Python/Coroutine.cs
- src/CSnakes.Runtime/Python/GeneratorIterator.cs
This PR fixes the visibility of `Coroutine` and `GeneratorIterator` family to types to be internal and removes them from the public API because they are implementation details. Only the interfaces they implement remain public and this is consistent with other types like `PyList`, `PyDictionary`, etc.
While this is a [breaking change](https://github.com/tonybaloney/CSnakes/issues/631), it was never expected for user code to instantiate and reference these.
> Fix visibility of Python type implementations
